name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          cd backend && npm install
          cd ../frontend && npm install

      - name: Run linters
        run: npm run lint

      # - name: Start frontend server
      #   run: CI=true npm start --prefix frontend &
      
      # - name: Wait for frontend server
      #   run: npx wait-on http://localhost:3000

      - name: Run tests
        env:
          JWT_SECRET: "test_secret"
        run: npm run test